name = "github-events"
main = "src/worker.js"
# compatibility_flags = ["python_workers"]
compatibility_date = "2024-04-01"

[[queues.producers]]
    queue = "cdevents-scm"
    binding = "SCM_QUEUE"
[[kv_namespaces]]
    id = "8467ca13e24c4834a445692ba105f101" # pragma: allowlist secret
    binding = "KV_APP"
